smileyBytes = bytearray('🙄', 'utf-8')
print(smileyBytes)
smileyByte = (b'\xf0\x9f\x99\x84')
print(smileyByte.decode('utf-8'))
smileyBytes[3] = int('80', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('81', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('82', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('83', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('85', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('86', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('87', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('88', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('89', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('90', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('91', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('92', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('93', 16,)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('94', 16,)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('95', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('96', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('97', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('98', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[3] = int('99', 16)
print(smileyBytes.decode('utf-8'))
smileyBytes[2] = int('80', 16)
print(smileyBytes.decode('utf-8'))